name: Test

on:
  workflow_dispatch:


jobs:
  test:
    name: test
    runs-on: [self-hosted, ubuntu-20.04, main]
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: | 
          ls -la